### ISSUE TITLE
DynamoDBModel should not add non-field attributes to item

### ISSUE THREAD

**Issue by joconor** [clearcare/cc_dynamodb3#15]
DynamoDBModel.__setattr__(), after invoking super, will set the attribute in its 'item' instance variable. Item is used as the basis for constructing the DynamoDB Item and as such, nothing should be added to item that is not defined as a DynamoDBModel field (i.e., exists in 'fields').

Currently, non-field attributes will be written to item, and when the model is saved, those non-field attributes will be attempted to be saved to DynamoDB. This usually (always?) results in an error.

Workaround: Add any non-field attributes to the FIELDS_SAFE_TO_OVERWRITE list for the subclass.

**Comment by pcraciunoiu** [comment]
@joconor actually I'm not able to reproduce this, you can try this test in `test_hash_only_model.py`:

```python
def test_non_field_set_on_item_then_get():
    HashOnlyModelFactory.create_table()
    obj = HashOnlyModelFactory(agency_subdomain='metzler', external_id=123)
    obj.non_field = 123
    obj.save()

    reloaded = HashOnlyModel.get(agency_subdomain='metzler')
    assert not reloaded.item.get('non_field')
```

**Comment by joconor** [comment]
Fixed in https://github.com/clearcare/cc_dynamodb3/pull/16
